version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: 12
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test
      - run: yarn lint
workflows:
    build-and-test:
      jobs:
        - build-and-test
